# Generated by Django 6.0.3 on 2026-03-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artworks/')),
                ('name', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('style', models.CharField(max_length=100)),
                ('context', models.TextField()),
                ('embedding', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('input_text', models.TextField(blank=True, null=True)),
                ('input_image', models.ImageField(blank=True, null=True, upload_to='chat/')),
                ('recognized_artwork', models.CharField(max_length=200)),
                ('similarity_score', models.FloatField()),
                ('model_response', models.TextField()),
            ],
        ),
    ]
