# Generated by Django 6.0.3 on 2026-03-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_artworkimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
