# Generated by Django 6.0.3 on 2026-03-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_remove_artwork_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='aliases',
            field=models.TextField(blank=True, default=''),
        ),
    ]
